### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by dicotom** [gnh1201/lotto_genetic_algorithm#4]
Set: Average time of function evaluating (secs): 0.14540128231048585 (total = 14.540128231048584)

Best score before optimization: -425

____________________ 0.4% GA is running...1 gen from 255...best value = -425Traceback (most recent call last):
  File "N:\DOWNLOADS\Roi Polanitzer GIT HUB LOTTERY FILES\LOTTERY PREDICTIONS\lotto_genetic_algorithm-main\lotto_genetic_algorithm-main\main.py", line 57, in <module>
    model.run(function=f)
  File "C:\Python312\Lib\site-packages\geneticalgorithm2\geneticalgorithm2.py", line 1056, in run
    ch2 = self.mut_middle(ch2, pvar1, pvar2)
  File "C:\Python312\Lib\site-packages\geneticalgorithm2\geneticalgorithm2.py", line 1186, in mut_middle
    x[i] = random.randint(v2, v1)
  File "C:\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
  File "C:\Python312\Lib\random.py", line 301, in randrange
    istart = _index(start)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by gnh1201** [comment]
Sorry for the late response, we will look into this matter soon.
